### ISSUE TITLE
CubeConnector copies properties error

### ISSUE THREAD

**Issue by shaoxt** [femtoframework/femto-service#3]
09:54:32.430 [Thread-6] WARN  apsis/cube/connector - Set property exception
org.femtoframework.lang.reflect.MethodInvocationException: Invoke method failed for:org.femtoframework.cube.spec.ConnectionSpec#setRemoteVersion
        at org.femtoframework.lang.reflect.Reflection.invoke(Reflection.java:831)
        at org.femtoframework.bean.info.ext.SimplePropertyInfo.invokeSetter(SimplePropertyInfo.java:181)
        at org.femtoframework.service.apsis.cube.CubeConnector.connect(CubeConnector.java:151)
        at org.bolango.galaxy.htcp.HTcpClientConnector.connect(HTcpClientConnector.java:261)
        at org.bolango.galaxy.htcp.HTcpClientConnector.connect(HTcpClientConnector.java:243)
        at org.bolango.galaxy.htcp.HTcpClientConnector.connect(HTcpClientConnector.java:200)
        at org.bolango.galaxy.htcp.HTcpClientConnector.run(HTcpClientConnector.java:145)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.femtoframework.lang.reflect.Reflection.invoke(Reflection.java:827)
        ... 7 common frames omitted

**Comment by shaoxt** [comment]
https://github.com/femtoframework/femto-service/commit/dd8e9e49ce8c031b7da7dade4c3ec3b14ca1b27d
